language: cpp  
      compiler: gcc 
      dist: trusty 
        
      before_install:  
       - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
       - sudo apt-get update -qq  
      install:   
       - sudo apt-get install -qq g++-6  
       - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90  
      script:   
       - g++ febin.cpp -o travis_gcc_cpp17  
        - ./travis_gcc_cpp17 
        - g++ AjeetDehal.cpp -o travis_gcc 
        - ./travis_gcc
        - g++ akshay.cpp -o travis_gc 
        - ./travis_gc
        - g++ himm.cpp -o travis_g
        - ./travis_g 
